version: '3.8'

services:
  postgres:
    image: 'postgres'
    container_name: 'db-container'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: '123'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'shop-app'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shopappdb'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
